/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Sesion;

import com.Sesion.modelo.beans.Usuario;
import com.Sesion.modelo.logic.UsuarioLogic;
import java.awt.GraphicsConfiguration;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class FrmRegistrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarUsuario
     */
    public FrmRegistrarUsuario(java.awt.Frame parentFrame, boolean modal) {
        super() ;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private FrmRegistrarUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   
      @SuppressWarnings("unchecked")
    

         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRepetircontraseña = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtContraseña1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(51, 153, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel1.setText("Registro de Usuarios");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setText("Repetir contraseña:");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 240, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel6.setText("Usuario:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        txtRepetircontraseña.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtRepetircontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepetircontraseñaActionPerformed(evt);
            }
        });
        bg.add(txtRepetircontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 310, 30));

        txtUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        bg.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 310, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel4.setText("Contraseña:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        bg.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 120, 50));

        btnRegistrar1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnRegistrar1.setText("Registrar");
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });
        bg.add(btnRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 120, 50));

        btnModificar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnModificar.setText("Modificar ");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        bg.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 120, 50));

        txtContraseña1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseña1ActionPerformed(evt);
            }
        });
        bg.add(txtContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 310, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/SimboloAutismotransparente1.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 510, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRepetircontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepetircontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepetircontraseñaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(!txtUsuario.getText().isEmpty()){
            
            
            if(UsuarioLogic.eliminar(txtUsuario.getText())){
                 JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente");
                 
                 FrmLogin frmLogin= new FrmLogin();
                frmLogin.setVisible(true);
                frmLogin.setLocationRelativeTo(null);
                this.setVisible(false);
                 
            }else{
                JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            }
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        if(!txtUsuario.getText().isEmpty()&&!txtContraseña1.getText().isEmpty()&&txtRepetircontraseña.getText().equals(txtContraseña1.getText())){
            
            Usuario usuario= new Usuario(txtUsuario.getText(),txtContraseña1.getText());
            if(UsuarioLogic.insertar(usuario)){
                 JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente");
                 
            FrmLogin frmLogin= new FrmLogin ();
            frmLogin.setVisible(true);
            frmLogin.setLocationRelativeTo(null);
            this.setVisible(false);
                                     
                 
            }else{
                JOptionPane.showMessageDialog(this, "Usuario ya existente");
            }
        }
                
        
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(!txtUsuario.getText().isEmpty()&&!txtContraseña1.getText().isEmpty()&&txtRepetircontraseña.getText().equals(txtContraseña1.getText())){
            
            Usuario usuario= new Usuario(txtUsuario.getText(),txtContraseña1.getText());
            if(UsuarioLogic.modificar(usuario)){
                 JOptionPane.showMessageDialog(this, "Usuario modificado exitosamente");
                FrmLogin frmLogin= new FrmLogin();
                frmLogin.setVisible(true);
                frmLogin.setLocationRelativeTo(null);
                this.setVisible(false);
                 
            }else{
                JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            }
        }
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseña1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtContraseña1;
    private javax.swing.JPasswordField txtRepetircontraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
