/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Sesion;


import java.io.InputStreamReader;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Scanner;

/**
 *
 * @author Acer
 */
public class Ventana3 extends javax.swing.JFrame {
    
    DoubleLinkedList<Activity> calendar2;

    /**
     * Creates new form Ventana3
     */
    public Ventana3(DoubleLinkedList<Activity> calendar) {
        initComponents();
        calendar2=calendar;
        this.setLocationRelativeTo(null);
    }
    public Ventana3() {
        initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTarea = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEtiqueta = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesubi = new javax.swing.JTextArea();
        radiobtnUrgente = new javax.swing.JRadioButton();
        radiobtnImportante = new javax.swing.JRadioButton();
        radiobtnPendiente = new javax.swing.JRadioButton();
        btnAgregaryVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(51, 153, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel6.setText("Ingrese la Hora:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel4.setText("Ingrese la Tarea:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setText("Seleccione la Prioridad");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel7.setText("Ingrese la Fecha:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtTarea.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtTarea.setText("Ir al gimnasio");
        txtTarea.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtTareaCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTareaActionPerformed(evt);
            }
        });
        bg.add(txtTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, 30));

        txtFecha.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtFecha.setText("YYYY-MM-DD");
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        bg.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, 30));

        txtHora.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtHora.setText("HH:MM:SS");
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        bg.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 230, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel11.setText("Ponga una etiqueta:");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        txtEtiqueta.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtEtiqueta.setText("Gym");
        txtEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEtiquetaActionPerformed(evt);
            }
        });
        bg.add(txtEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 230, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel12.setText("Agregue una descripción /ubicación: ");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/SimboloAutismotransparente1.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 230));

        txtDesubi.setColumns(20);
        txtDesubi.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtDesubi.setRows(5);
        txtDesubi.setText("Descripción");
        jScrollPane1.setViewportView(txtDesubi);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 520, 100));

        buttonGroup1.add(radiobtnUrgente);
        radiobtnUrgente.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        radiobtnUrgente.setText("Urgente");
        radiobtnUrgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnUrgenteActionPerformed(evt);
            }
        });
        bg.add(radiobtnUrgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        buttonGroup1.add(radiobtnImportante);
        radiobtnImportante.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        radiobtnImportante.setText("Importante");
        bg.add(radiobtnImportante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        buttonGroup1.add(radiobtnPendiente);
        radiobtnPendiente.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        radiobtnPendiente.setText("Pendiente");
        bg.add(radiobtnPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        btnAgregaryVolver.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnAgregaryVolver.setText("Agregar y volver al menú inicial");
        btnAgregaryVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregaryVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregaryVolverMouseClicked(evt);
            }
        });
        btnAgregaryVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaryVolverActionPerformed(evt);
            }
        });
        bg.add(btnAgregaryVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 330, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTareaActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtTareaCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtTareaCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTareaCaretPositionChanged

    private void txtEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEtiquetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEtiquetaActionPerformed

    private void radiobtnUrgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnUrgenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnUrgenteActionPerformed

    private void btnAgregaryVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregaryVolverMouseClicked
        // TODO add your handling code here:
        
        
        int prioridad = 0;
        //String Description;
        
        //boolean type;
        
       
        
        //DoubleLinkedList<Activity> calendar;
        //calendar = new DoubleLinkedList<Activity>();

        String name = txtTarea.getText();
        String label = txtEtiqueta.getText();
        String date = txtFecha.getText();
        String hour = txtHora.getText();
        String Ubication = txtDesubi.getText();
        

        if (radiobtnUrgente.isSelected() == true)
            prioridad=0;
        if (radiobtnImportante.isSelected() == true)
            prioridad=1;
        if (radiobtnPendiente.isSelected() == true) 
            prioridad=2;
        

        if (Ubication == null) {
            calendar2.pushBack(new Event(name, LocalDate.parse(date), LocalTime.parse(hour), Priority.values()[prioridad], label));
        } else {
            calendar2.pushBack(new Event(name, LocalDate.parse(date), LocalTime.parse(hour), Priority.values()[prioridad], label, Ubication));
        }
        
        Sesion s = new Sesion (calendar2);
        s.setVisible(true);
        s.setLocationRelativeTo(null);
        this.setVisible(false); 

        
    }//GEN-LAST:event_btnAgregaryVolverMouseClicked

    private void btnAgregaryVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaryVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregaryVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAgregaryVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiobtnImportante;
    private javax.swing.JRadioButton radiobtnPendiente;
    private javax.swing.JRadioButton radiobtnUrgente;
    private javax.swing.JTextArea txtDesubi;
    private javax.swing.JTextField txtEtiqueta;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtTarea;
    // End of variables declaration//GEN-END:variables
}
