/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import interfaz.Sesion;
import proyecto1.Activity;
import estructuras.DoubleLinkedList;

/**
 *
 * @author Acer
 */
public class Ventana2 extends javax.swing.JFrame {
    
    DoubleLinkedList<Activity> calendar2;

    /**
     * Creates new form Ventana2
     */
    public Ventana2(DoubleLinkedList<Activity> calendar) {
        initComponents();
        calendar2=calendar;
    }
    public Ventana2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        actButton = new javax.swing.JButton();
        eventButton = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(51, 153, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("¿Qué desea agregar?");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButton.setText("Volver");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        bg.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 110, 40));

        actButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        actButton.setText("Actividad");
        actButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actButtonMouseClicked(evt);
            }
        });
        bg.add(actButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 110, 40));

        eventButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eventButton.setText("Evento");
        eventButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eventButtonMouseClicked(evt);
            }
        });
        bg.add(eventButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 110, 40));

        image.setBackground(new java.awt.Color(255, 255, 255));
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/SimboloAutismotransparente1.png"))); // NOI18N
        bg.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 510, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actButtonMouseClicked
        Ventana3 c= new Ventana3 (calendar2);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_actButtonMouseClicked

    private void eventButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventButtonMouseClicked
        Ventana3 c= new Ventana3 (calendar2);
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eventButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        Sesion s = new Sesion (calendar2);
        s.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_backButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actButton;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel bg;
    private javax.swing.JButton eventButton;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
