/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;


import interfaz.Sesion;
import java.io.InputStreamReader;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Scanner;
import proyecto1.Activity;
import estructuras.DoubleLinkedList;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import proyecto1.Event;
import proyecto1.Priority;

/**
 *
 * @author Acer
 */
public class Ventana3 extends javax.swing.JFrame {
    
    DoubleLinkedList<Activity> calendar2;

    /**
     * Creates new form Ventana3
     * @param calendar
     */
    public Ventana3(DoubleLinkedList<Activity> calendar) {
        initComponents();
        calendar2=calendar;
    }
    public Ventana3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        timePicker = new com.github.lgooddatepicker.components.TimePicker();
        datePicker = new com.github.lgooddatepicker.components.DatePicker();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        taskTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        labelTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        locationTextField = new javax.swing.JTextArea();
        radiobtnUrgente = new javax.swing.JRadioButton();
        radiobtnImportante = new javax.swing.JRadioButton();
        radiobtnPendiente = new javax.swing.JRadioButton();
        addAndReturnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(51, 153, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg.add(timePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 230, 30));
        bg.add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel6.setText("Ingrese la Hora:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel4.setText("Ingrese la Tarea:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setText("Seleccione la Prioridad");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel7.setText("Ingrese la Fecha:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        taskTextField.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        taskTextField.setForeground(new java.awt.Color(204, 204, 204));
        taskTextField.setText("Nombre de la tarea");
        taskTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taskTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                taskTextFieldFocusLost(evt);
            }
        });
        taskTextField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                taskTextFieldCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        taskTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskTextFieldActionPerformed(evt);
            }
        });
        bg.add(taskTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel11.setText("Ponga una etiqueta:");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        labelTextField.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        labelTextField.setForeground(new java.awt.Color(204, 204, 204));
        labelTextField.setText("Etiqueta");
        labelTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                labelTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                labelTextFieldFocusLost(evt);
            }
        });
        labelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelTextFieldActionPerformed(evt);
            }
        });
        bg.add(labelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 230, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel12.setText("Agregue una descripción /ubicación: ");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/SimboloAutismotransparente1.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 230));

        locationTextField.setColumns(20);
        locationTextField.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        locationTextField.setForeground(new java.awt.Color(204, 204, 204));
        locationTextField.setRows(5);
        locationTextField.setText("Descripción");
        locationTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                locationTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                locationTextFieldFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(locationTextField);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 520, 100));

        buttonGroup1.add(radiobtnUrgente);
        radiobtnUrgente.setText("Urgente");
        radiobtnUrgente.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        radiobtnUrgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnUrgenteActionPerformed(evt);
            }
        });
        bg.add(radiobtnUrgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        buttonGroup1.add(radiobtnImportante);
        radiobtnImportante.setText("Importante");
        radiobtnImportante.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        bg.add(radiobtnImportante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        buttonGroup1.add(radiobtnPendiente);
        radiobtnPendiente.setText("Pendiente");
        radiobtnPendiente.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        bg.add(radiobtnPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        addAndReturnButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addAndReturnButton.setText("Agregar y Volver");
        addAndReturnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAndReturnButtonMouseClicked(evt);
            }
        });
        bg.add(addAndReturnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taskTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskTextFieldActionPerformed

    private void taskTextFieldCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_taskTextFieldCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_taskTextFieldCaretPositionChanged

    private void labelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelTextFieldActionPerformed

    private void radiobtnUrgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnUrgenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnUrgenteActionPerformed

    private void addAndReturnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAndReturnButtonMouseClicked
        int prioridad = 0;
        //String Description;
        
        //boolean type;
        
       
        
        //DoubleLinkedList<Activity> calendar;
        //calendar = new DoubleLinkedList<Activity>();

        String name = taskTextField.getText();
        String label = labelTextField.getText();
        //String date = txtFecha.getText();
        LocalDate date = datePicker.getDate();
        //String hour = txtHora.getText();
        LocalTime hour = timePicker.getTime();
        String Ubication = locationTextField.getText();
        

        if (radiobtnUrgente.isSelected() == true)
            prioridad=0;
        if (radiobtnImportante.isSelected() == true)
            prioridad=1;
        if (radiobtnPendiente.isSelected() == true) 
            prioridad=2;
        

        if (Ubication == null) {
            calendar2.pushBack(new Event(name, date, hour, Priority.values()[prioridad], label));
        } else {
            calendar2.pushBack(new Event(name, date, hour, Priority.values()[prioridad], label, Ubication));
        }
        
        Sesion s = new Sesion (calendar2);
        s.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_addAndReturnButtonMouseClicked

    private void taskTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taskTextFieldFocusGained
        if(taskTextField.getText().equals("Nombre de la tarea")){
            taskTextField.setText("");
            taskTextField.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_taskTextFieldFocusGained

    private void taskTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taskTextFieldFocusLost
        if(taskTextField.getText().equals("")){
            taskTextField.setText("Nombre de la tarea");
            taskTextField.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_taskTextFieldFocusLost

    private void labelTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_labelTextFieldFocusGained
        if(labelTextField.getText().equals("Etiqueta")){
            labelTextField.setText("");
            labelTextField.setForeground(Color.black);
        }
    }//GEN-LAST:event_labelTextFieldFocusGained

    private void labelTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_labelTextFieldFocusLost
        if(labelTextField.getText().equals("")){
            labelTextField.setText("Etiqueta");
            labelTextField.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_labelTextFieldFocusLost

    private void locationTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationTextFieldFocusGained
        if(locationTextField.getText().equals("Descripción")){
            locationTextField.setText("");
            locationTextField.setForeground(Color.black);
        }
    }//GEN-LAST:event_locationTextFieldFocusGained

    private void locationTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_locationTextFieldFocusLost
        if(locationTextField.getText().equals("")){
            locationTextField.setText("Descripción");
            locationTextField.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_locationTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAndReturnButton;
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.github.lgooddatepicker.components.DatePicker datePicker;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField labelTextField;
    private javax.swing.JTextArea locationTextField;
    private javax.swing.JRadioButton radiobtnImportante;
    private javax.swing.JRadioButton radiobtnPendiente;
    private javax.swing.JRadioButton radiobtnUrgente;
    private javax.swing.JTextField taskTextField;
    private com.github.lgooddatepicker.components.TimePicker timePicker;
    // End of variables declaration//GEN-END:variables
}
